version: '3.9'

services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=august
      - POSTGRES_PASSWORD=Kommikarp3
      - POSTGRES_DB=argpuu
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    networks:
      - appnet

  web:
    build: .
    command: gunicorn argpuu.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./argpuu:/app
      - static_volume:/vol/web/staticfiles
      - media_volume:/vol/web/media
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - appnet
    ports:
      - "8000:8000"

  nginx:
    image: nginx:1.25
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - static_volume:/vol/web/staticfiles
      - media_volume:/vol/web/media
    depends_on:
      - web
    networks:
      - appnet

volumes:
  postgres_data:
  static_volume:
  media_volume:

networks:
  appnet:
