services:
  web:
    build: .
    command: >
      sh -c "npm run build &&
            python manage.py collectstatic --noinput &&
            python manage.py makemigrations --noinput &&
            python manage.py migrate &&
            python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    stdin_open: true
    tty: true


  db:
    image: postgres:15
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  postgres_data:
