# Generated by Django 5.1.4 on 2025-06-08 20:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("argument_map_app", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="argumentmap",
            name="auhtorized_viewers",
            field=models.ManyToManyField(
                blank=True,
                related_name="authorized_viewers_argument_maps",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="argumentmap",
            name="authorized_editors",
            field=models.ManyToManyField(
                blank=True,
                related_name="authorized_editors_argument_maps",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
