# Generated by Django 5.1.4 on 2025-06-08 20:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('argument_map_app', '0002_argumentmap_auhtorized_viewers_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='argumentmap',
            name='auhtorized_viewers',
        ),
        migrations.RemoveField(
            model_name='argumentmap',
            name='authorized_editors',
        ),
        migrations.AddField(
            model_name='argumentmap',
            name='editors',
            field=models.ManyToManyField(blank=True, related_name='editors_argument_maps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='argumentmap',
            name='viewers',
            field=models.ManyToManyField(blank=True, related_name='viewers_argument_maps', to=settings.AUTH_USER_MODEL),
        ),
    ]
